---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Othello AI application infrastructure'
Parameters:
  KeyName:
    Description: 'Key Pair name'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: myKey

  CIDRForSSH:
    Description: 'CIDR allowed to ssh'
    Type: 'String'
    Default: '0.0.0.0/0'

  DBPassword:
    Description: 'Database password'
    Type: 'String'
    Default: 'dbpassword'

  StartSchedule:
    Description: 'Time to start this application'
    Type: 'String'
    Default: 'cron(45 0 * * ? *)'

  StopSchedule:
    Description: 'Time to stop this application'
    Type: 'String'
    Default: 'cron(15 11 * * ? *)'


Resources:

### Network ###
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsHostnames: true

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}

  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  VMSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: '10.0.56.0/24'
      VpcId: !Ref VPC

  VMSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: '10.0.57.0/24'
      VpcId: !Ref VPC

  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC

  RouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref VMSubnet1
      RouteTableId: !Ref RouteTable

  RouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref VMSubnet2
      RouteTableId: !Ref RouteTable

  RoutePublicSubnetToInternet:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway
    DependsOn: 
      - VPCGatewayAttachment


### Load balancer ###
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Type: application
      Subnets:
        - Ref: VMSubnet1
        - Ref: VMSubnet2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Scheme: 'internet-facing'
    DependsOn: VPCGatewayAttachment

  LoadBalancerListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoadBalancerTargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  LoadBalancerTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: '/othello/isBusy'
      HealthCheckPort: '80'
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-299'
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: !Ref WebServer1
          Port: 80
        - Id: !Ref WebServer2
          Port: 80
      VpcId: !Ref VPC

  LoadBalancerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Load balancer security group'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80


### Web server ###
  WebServer1:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-09d28faae2e9e7138'
      InstanceType: 't2.micro'
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref VMSubnet1
          DeviceIndex: '0'
          GroupSet:
            - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: 'othelloApp.WebServerInstance1'
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x
          yum -y update
          
          # web server setup
          curl -s https://raw.githubusercontent.com/E-Kohei/tmpAWS/main/othello-server/webserver-setup.sh | bash -ex
          
          # create database for django application
          # this operation is done by either of the two machines
          yum -y install mysql-community-client
          while ! nc -z ${Database.Endpoint.Address} 3306; do sleep 10; done
          sleep 10
          mysql --user=ekohei --host=${Database.Endpoint.Address} --password=${DBPassword} --database=othello --execute="CREATE TABLE records (id INTEGER PRIMARY KEY AUTO_INCREMENT, date_time CHAR(20) NOT NULL, dark_player VARCHAR(11) NOT NULL, light_player VARCHAR(11) NOT NULL, dark_score SMALLINT NOT NULL, light_score SMALLINT NOT NULL, moves VARCHAR(250) NOT NULL);"
          
          # Notify CloudFormation that the script ended
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServer1 --region ${AWS::Region}
    DependsOn:
      - VPCGatewayAttachment

  WebServer2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-09d28faae2e9e7138'
      InstanceType: 't2.micro'
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref VMSubnet2
          DeviceIndex: '0'
          GroupSet:
            - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: 'othelloApp.WebServerInstance2'
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x
          yum -y update
          
          # web server setup
          curl -s https://raw.githubusercontent.com/E-Kohei/tmpAWS/main/othello-server/webserver-setup.sh | bash -ex
          
          # Notify CloudFormation that the script ended
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServer2 --region ${AWS::Region}
    DependsOn:
      - VPCGatewayAttachment
  
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'web server security group'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: !Sub ${CIDRForSSH}
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
          IpProtocol: tcp 
          FromPort: 80
          ToPort: 80


### Database ###
  Database:
    Type: 'AWS::RDS::DBInstance'
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: '5'
      BackupRetentionPeriod: 0
      DBInstanceClass: 'db.t2.micro'
      DBName: othello
      Engine: MySQL
      MasterUsername: ekohei
      MasterUserPassword: !Sub ${DBPassword}
      VPCSecurityGroups:
        - !Sub ${DatabaseSecurityGroup.GroupId}
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: Name
          Value: 'othelloApp.DBInstance'
    DependsOn: VPCGatewayAttachment

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'DB subnet group'
      SubnetIds:
        - Ref: VMSubnet1
        - Ref: VMSubnet2

  DatabaseSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'database security group'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref WebServerSecurityGroup
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306


### Lambda functions ###
  FunctionStartInstances:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: python3.8
      Role: !GetAtt RoleStartStopInstances.Arn
      Handler: index.lambda_handler
      Timeout: 60
      Description: 'Starts EC2 and RDS instances'
      Code:
        ZipFile: |
          import boto3
          from botocore.exceptions import ClientError
          
          ec2 = boto3.client("ec2", region_name="ap-northeast-1")
          rds = boto3.client("rds", region_name="ap-northeast-1")

          def search_db_by_tag(dbInstances, tagKey, tagValue, onlyKey=False):
              result = []
              if onlyKey:
                  # search for tag key
                  for instance in dbInstances:
                      if tagKey in [tag["Key"] for tag in instance["TagList"]]:
                          result.append(instance)
              else:
                  # search for tag which matches both of key and value
                  for instance in dbInstances:
                      if {"Key":tagKey, "Value":tagValue} in instance["TagList"]:
                         result.append(instance)
              return result


          def lambda_handler(event, context):
              webservers = ec2.describe_instances(
                  Filters=[{
                      'Name': 'tag:Name',
                      'Values': ['othelloApp.WebServerInstance*']
                  }]
              )["Reservations"]
              instanceIds = [reservation["Instances"][0]["InstanceId"]
                             for reservation in webservers]
            
              dbInstances = search_db_by_tag(
                  rds.describe_db_instances()["DBInstances"],
                  "Name", "othelloApp.DBInstance"
              )
              dbInstanceIds = [instance["DBInstanceIdentifier"]
                               for instance in dbInstances]
            
              try:
                  ec2.start_instances(InstanceIds=instanceIds, DryRun=True)
              except ClientError as ce:
                  if 'DryRunOperation' not in str(ce):
                      raise
            
              # Dry run succeeded, run start_instances without dryrun
              try:
                  response = ec2.start_instances(
                      InstanceIds=instanceIds,
                      DryRun=False
                  )
                  print("started web servers")
                  for dbInstanceId in dbInstanceIds:
                      dbResponse = rds.start_db_instance(
                          DBInstanceIdentifier=dbInstanceId
                      )
                  print("started db instances")
              except ClientError as ce:
                  print(ce)
              except Exception as e:
                  print(e)

  FunctionStopInstances:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: python3.8
      Role: !GetAtt RoleStartStopInstances.Arn
      Handler: index.lambda_handler
      Timeout: 60
      Description: 'Stops EC2 and RDS instances'
      Code:
        ZipFile: |
          import boto3
          from botocore.exceptions import ClientError

          ec2 = boto3.client("ec2", region_name="ap-northeast-1")
          rds = boto3.client("rds", region_name="ap-northeast-1")

          def search_db_by_tag(dbInstances, tagKey, tagValue, onlyKey=False):
              result = []
              if onlyKey:
                  # search for tag key
                  for instance in dbInstances:
                      if tagKey in [tag["Key"] for tag in instance["TagList"]]:
                          result.append(instance)
              else:
                  # search for tag which matches both of key and value
                  for instance in dbInstances:
                      if {"Key":tagKey, "Value":tagValue} in instance["TagList"]:
                          result.append(instance)
              return result


          def lambda_handler(event, context):
              webservers = ec2.describe_instances(
                  Filters=[{
                      'Name': 'tag:Name',
                      'Values': ['othelloApp.WebServerInstance*']
                  }]
              )["Reservations"]
              instanceIds = [reservation["Instances"][0]["InstanceId"]
                              for reservation in webservers]
            
              dbInstances = search_db_by_tag(
                  rds.describe_db_instances()["DBInstances"],
                  "Name", "othelloApp.DBInstance"
              )
              dbInstanceIds = [instance["DBInstanceIdentifier"]
                               for instance in dbInstances]

              try:
                  ec2.stop_instances(InstanceIds=instanceIds, DryRun=True)
              except ClientError as ce:
                  if 'DryRunOperation' not in str(ce):
                      raise
            
              # Dry run succeeded, run stop_instances without dryrun
              try:
                  response = ec2.stop_instances(
                      InstanceIds=instanceIds,
                      DryRun=False
                  )
                  print("stopped web servers")
                  for dbInstanceId in dbInstanceIds:
                      dbResponse = rds.stop_db_instance(
                          DBInstanceIdentifier=dbInstanceId
                      )
                  print("stopped db instance")
              except ClientError as ce:
                  print(ce)
              except Exception as e:
                  print(e)

  PermissionStartInstances:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt FunctionStartInstances.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt RuleScheduledStart.Arn

  PermissionStopInstances:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt FunctionStopInstances.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt RuleScheduledStop.Arn

  RuleScheduledStart:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Scheduled rule to start application'
      ScheduleExpression: !Ref StartSchedule
      State: 'ENABLED'
      Targets:
        - Arn: !GetAtt FunctionStartInstances.Arn
          Id: 'StartFunction'

  RuleScheduledStop:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Scheduled rule to stop application'
      ScheduleExpression: !Ref StopSchedule
      State: 'ENABLED'
      Targets:
        - Arn: !GetAtt FunctionStopInstances.Arn
          Id: 'StopFunction'

  RoleStartStopInstances:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: StartStopInstancePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 'ec2:Describe*'
                  - 'ec2:Start*'
                  - 'ec2:Stop*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'rds:Describe*'
                  - 'rds:Start*'
                  - 'rds:Stop*'
                Resource: '*'
                
 
 

Outputs:
  LoadBalancerURL:
    Value: !Sub 'http://${LoadBalancer.DNSName}'
    Description: 'Othello app URL'
  WebServerIPAddress1:
    Value: !Sub '${WebServer1.PublicIp}'
    Description: 'Dns name of web server 1 for ssh'
  WebServerIPAddress2:
    Value: !Sub '${WebServer2.PublicIp}'
    Description: 'Dns name of web server 2 for ssh'
  DatabasePrivateURL:
    Value: !Sub '${Database.Endpoint.Address}'

